# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EyDxshURiyb75YfnEqUo_NU1yjTKvkb
"""

from textblob import TextBlob
t = "i have finished my work"
sentiment=TextBlob(t).sentiment
print(sentiment)

#1. Import dataset
#2. Categorical to Numerical (Sentiment Column)
#3. Preprocessing - Remove HTML
#4. Lower Case Conversion
#5. Remove Special Characters
#6. Stop Word Removal
#7. Stemming Process
#8. Joining the list of words
#9. Feature Extraction using count vectorize
#10. Train Test Split
#11. Create Algorithm
#12. Fit the Training Data
#13. Predict the testing data
#14. Performance Evaluation (Accuracy)

import pandas as pd

df=pd.read_csv('IMDB Dataset.csv', nrows=5000, encoding='latin1')
df.head(10)

df.tail()

df.describe()

df.info()

df.shape

df.fillna(0,inplace=True)

df.info()

df['review'][1]

df['sentiment'].replace('positive',1,inplace=True)
df['sentiment'].replace('negative',0,inplace=True)

df.head()

import re
print(df.iloc[2].review)

clean=re.compile('<.*?>')
print(re.sub(clean,'',df.iloc[1].review))

def clean_html(text):
  clean=re.compile('<.*?>')
  return re.sub(clean,'',text)

df['review']=df['review'].apply(clean_html)

df.head()

def convert_lower(text):
  return text.lower()

df['review']=df['review'].apply(convert_lower)

df.head()

def remove_special(text):
  x=''
  for i in text:
    if i.isalnum():
      x=x+i
    else:
      x=x+' '
  return x

remove_special("Th%e @ classic use of the word. it is called oz as that is the nickname given to the oswald maximum")

df['review']=df['review'].apply(remove_special)

df.head()

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stopwords.words('english')

def remove_stopwords(text):
  x=[]
  for i in text.split():
    if i not in stopwords.words('english'):
      x.append(i)
  y=x[:]
  x.clear()
  return y

df['review']=df['review'].apply(remove_stopwords)

print (df.head())

y=[]
from nltk.stem import PorterStemmer
ps=PorterStemmer()
def stem_words(text):
  for i in text:
    y.append(ps.stem(i))
  z=y[:]
  y.clear()
  return z

stem_words(['I','loved','loving','went','mentioned'])

df['review']=df['review'].apply(stem_words)

df.head()

def join_back(list_input):
  return " ".join(list_input)

df['review']=df['review'].apply(join_back)

df.head()

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=150)

X=cv.fit_transform(df['review']).toarray()

X[1:5,:]

X.shape

y=df.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

X_train.shape

y_train.shape

X_test.shape

y_test.shape

from sklearn.naive_bayes import GaussianNB
clf1=GaussianNB()
clf1.fit(X_train,y_train)

y_pred1=clf1.predict(X_test)

from sklearn.metrics import accuracy_score
print("Gaussian", accuracy_score(y_test,y_pred1))

from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=100, random_state=42)
clf1.fit(X_train,y_train)

y_pred1=clf1.predict(X_test)
from sklearn.metrics import accuracy_score
print("Random Forest", accuracy_score(y_test,y_pred1))

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy', random_state=1)
model.fit(X_train, y_train)
y_pred2 = model.predict(X_test)
from sklearn.metrics import accuracy_score
print("Decision Tree", accuracy_score(y_test,y_pred2))

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
y_pred3 = model.predict(X_test)
from sklearn.metrics import accuracy_score
print("KNN", accuracy_score(y_test,y_pred3))

from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred4 = model.predict(X_test)
from sklearn.metrics import accuracy_score
print("SVC", accuracy_score(y_test,y_pred4))

new_review = '''This movie was not very well directed. they almost totally disregarded the book.I guess they were trying 2 save time. the only upside 2 me was that the actor who played finny was cute. Some of the dialog between the main characters appeared a little gay which was not the case in the book. Major parts of the book were once again chopped out.You lost the over all effect it was not as haunting as the book and left me lacking severely. Also the strong language although it was brief was very unnecessary. Also i was surprised ( not pleasantly) by a new character that was no where in the book.One of my favorite characters (leper) was poorly interpreted and portrayed. He seemed more sinister in the movie than the real leper was in the book. Over all disappointing.'''

# Redefine stem_words to use a local variable instead of the global 'y'
# The original stem_words function was defined in cell OG_C0k0oCEQ1 and used a global 'y'.
# This caused a conflict when 'y' was later reassigned to df.iloc[:,-1].values (a numpy array).
# To fix this, we should make the list for collecting stemmed words local to the function.

def stem_words(text):
  local_stemmed_words = [] # Use a local variable here
  for i in text:
    local_stemmed_words.append(ps.stem(i))
  return local_stemmed_words

def preprocess_review(review):
    # Clean HTML
    review = clean_html(review)
    print("clean html", review)
    # Convert to lowercase
    review = convert_lower(review)
    print("convert lower", review)
    # Remove special characters
    review = remove_special(review)
    print("remove_special ", review)
    # Remove stopwords
    review_words = remove_stopwords(review)
    print("remove_stopwords ", review_words)
    # Stem words
    review_stemmed = stem_words(review_words) # This now calls the locally fixed stem_words
    print("stem_words ", review_stemmed)
    # Join back to string
    review = join_back(review_stemmed)
    print("join_back ", review)
    return review

processed_new_review = preprocess_review(new_review)

# Vectorize the preprocessed review
X_new = cv.transform([processed_new_review]).toarray()

# Predict the sentiment
prediction = clf1.predict(X_new)
print(prediction)

if prediction[0] == 1:
    print(f"The review '{new_review}' is predicted as: Positive")
else:
    print(f"The review '{new_review}' is predicted as: Negative")